### ISSUE TITLE
跨域被拦截了。。

### ISSUE THREAD

**Issue by MythHack** [overtrue/weibo-dogs-killer#7]
Failed to load https://weibo.com/aj/filter/block?ajwvr=6: Redirect from 'https://weibo.com/aj/filter/block?ajwvr=6' to 'https://passport.weibo.com/visitor/visitor?entry=miniblog&a=enter&url=https%3A%2F%2Fweibo.com%2Faj%2Ffilter%2Fblock%3Fajwvr%3D6&domain=.weibo.com&sudaref=http%3A%2F%2Fweibo.com%2Fmythhack%2Fhome%3Ftopnav%3D1%26wvr%3D6%26is_search%3D1%26key_word%3D%2522&ua=php-sso_sdk_client-0.6.23&_rand=1507785185.7428' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://weibo.com' is therefore not allowed access.

**Comment by overtrue** [comment]
从 https://weibo.com  登录， https
